name: CLI Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 9.13.2
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: Install modules
              run: pnpm i
            - name: Build create-springboard-app CLI
              run: npm run prepublishOnly
              working-directory: ./packages/springboard/create-springboard-app
            - name: Install Verdaccio
              run: npm install -g verdaccio
            - name: Start Verdaccio
              run: |
                verdaccio --config ./verdaccio/config/config.yaml > verdaccio.log 2>&1 & echo $! > verdaccio.pid
                for i in {1..10}; do
                  if curl -s http://localhost:4873/-/ping > /dev/null; then
                    echo "Verdaccio is up"
                    break
                  fi
                  echo "Waiting for Verdaccio..."
                  sleep 2
                done

            - name: Set npm registry to Verdaccio
              run: npm config set registry http://localhost:4873
            - name: Configure authentication for Verdaccio
              run: |
                echo "registry=http://localhost:4873/" > ~/.npmrc
                echo "//localhost:4873/:_authToken=fake" >> ~/.npmrc

            - name: Publish create-springboard-app CLI
              run: ./scripts/run-all-folders.sh 0.2.0 --mode verdaccio
            - name: Install create-springboard-app CLI
              run: npm install -g create-springboard-app
              env:
                NPM_CONFIG_REGISTRY: http://localhost:4873
            - name: Verify version is 0.2.0
              run: |
                if [ "$(create-springboard-app --version)" != "0.2.0" ]; then
                    echo "Version is not 0.2.0"
                    exit 1
                fi

            - name: Create a new app
              run: mkdir test-app && cd test-app && create-springboard-app
              env:
                NPM_CONFIG_REGISTRY: http://localhost:4873
            - name: Build App
              run: npm run build
              working-directory: ./test-app

            - name: Display Verdaccio logs on failure
              if: failure()
              run: |
                echo "Verdaccio logs:"
                cat verdaccio.log

            - name: Stop Verdaccio
              if: always()
              run: kill $(cat verdaccio.pid) || true
