name: Build Tauri All Platforms

on:
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            tauri_target: 'aarch64-apple-darwin'
            pkg_target: 'node20-macos-arm64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            tauri_target: 'x86_64-apple-darwin'
            pkg_target: 'node20-macos-x64'
          - platform: 'ubuntu-22.04'
            args: ''
            tauri_target: ''
            pkg_target: 'node20-linux-x64'
          - platform: 'windows-latest'
            args: ''
            tauri_target: ''
            pkg_target: 'node20-windows-x64'

    uses: ./.github/workflows/desktop_build.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      tauri_args: ${{ matrix.args }}
      tauri_target: ${{ matrix.tauri_target }}
      pkg_target: ${{ matrix.pkg_target }}
      sign_app: false
      # sign_app: true
      # APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      # APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      # APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      # APPLE_ID: ${{ secrets.APPLE_ID }}
      # APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      scaffold_tauri_project: true
      scaffold_tauri_project_config_path: './configs/tauri_project_config.json'
